version: '3'

services:
  apache:
    image: httpd:2.4
    container_name: demo_apache
    ports:
      - "8080:80"
    volumes:
      - ./apache-data:/usr/local/apache2/htdocs/
    networks:
      demo_net:
        ipv4_address: 172.20.0.2

  php:
    image: php:8.0-apache
    container_name: demo_php
    ports:
      - "8081:80"
    volumes:
      - ./php-data:/var/www/html/
    networks:
      demo_net:
        ipv4_address: 172.20.0.3

networks:
  demo_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16